### ISSUE TITLE
Initial Release Plan

### ISSUE THREAD

**Issue by tgross35** [RustCrypto/JOSE#24]
This is a quick outline of what I think is blocking for each crate's release:

- [ ] Question for all crates: #18

- [ ] `jose-b64`: Ready to go with some documentation updates (#19)
- [ ] `jose-jwa`: Ready to go with some documentation updates (#20)
- [ ] `jose-jwe`: Not yet started
- [ ] `jose-jwk`: Mostly ready to go
  - [ ] Documentation updates (#21)
  - [ ] RSA update
- [ ] `jose-jws`: Near ready to go
  - [ ] Documentation updates (#23)
  - [ ] Requires unit tests
  - [ ] RSA update (transitive via `jose-jwk`)
- [ ] `jose-jwt`: Not yet started
- [ ] `jose`: probably want to wait on all other crates to architect this one

The RSA dependency was mentioned by @tarcieri, any crates that need it shouldn't be released until the next version of the `rsa` crate is ready (soon)

**Comment by tgross35** [comment]
@tarcieri feel free to edit this as you see fit, I just kind of wanted to collect what I think the status of the different crates are

**Comment by tarcieri** [comment]
Looks good so far

**Comment by tarcieri** [comment]
I published v0.1.0 releases of the following crates largely as-is:

- `jose-b64`
- `jose-alg`
- `jose-jwk`
- `jose-jws`

We didn't quite tick all of your checkboxes and I think this is still a good list to keep for other reasons as work items.

If you need breaking changes of any of them, no worries, we can publish v0.2.

**Comment by a7g4** [comment]
Is anyone taking a stab at `jose-jwt`? I am writing a replacement for https://github.com/JadedBlueEyes/jsonwebtoken which appears unmaintained so I could try to build it to fit whatever API/architecture is planned for `jose-jwt`?

**Comment by tarcieri** [comment]
@a7g4 feel free to open a PR

**Comment by a7g4** [comment]
I'll start! 

Is there a good place to hash out a plan or design beforehand? I saw that @jacob-phantom started a MR series which seems to also be preparation for implementing `jose-jwt`

I haven't worked in the RustCrypto crates much before so sorry if this is documented somewhere.
